# server configuration
server:
  port: 9191

# endpoint configuration
endpoints:
  shutdown:
    enabled: true

# database configuration
flyway:
  baselineOnMigrate: true
  baseline-on-migrate: true
spring:
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
  flyway:
    baselineOnMigrate: true
    baseline-on-migrate: true

operationsmysql:
  datasource:
    core:
      host: localhost
      port: 3306
      schema: tenants
      username: root
      password: ethieTieCh8ahv
    common:
      protocol: jdbc
      subprotocol: mysql
      driverclass_name: com.mysql.cj.jdbc.Driver
token:
  user:
    access-validity-seconds: 600
    refresh-validity-seconds: 43200
  client:
    access-validity-seconds: 3600
    channel:
      secret: "p1234"
tenants: "gorilla,lion"
# Status Callback configuration for Twilio. Port will be taken from server configuration
hostconfig:
  host: localhost
  protocol: http

callbackconfig:
  host: 0.0.0.0
  protocol: http
  port: 5000

application:
  version: 1.0.0

management:
  endpoint:
    health:
      probes:
        enabled: true
      liveness:
        enabled: true
      readiness:
        enabled: true

providerSource:
  fromdatabase: disabled
  fromyml: enabled

providerKeys:
  telerivetApiKey: eKiC1_JWdKy7eaTGQFHxXXjXjacr60W9Zntl
  telerivetProjectId: PJ5ff552ce01d2978c

provider:
  enabled: true
  id: 2

operationsconfig:
  tenantid: "Fineract-Platform-TenantId"
  tenantidvalue : "default"
  tenantappkey: "Fineract-Tenant-App-Key"
  tenantappvalue: "123456543234abdkdkdkd"


logging:
  level:
    org:
      apache:
        camel=DEBUG:
    root: INFO


camel:
  server-port: 5009
  springboot:
    main-run-controller: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true
zeebe:
  client:
    max-execution-threads: 100
    number-of-workers: 5
    evenly-allocated-max-jobs: "#{${zeebe.client.max-execution-threads} / ${zeebe.client.number-of-workers}}"
    ttl: 30000
    security:
      plaintext: true
  broker:
    contactpoint: "zeebe-zeebe-gateway:26500"
  worker:
    timer: "PT15S"
    retries: 3