# server configuration
server:
  port: 9191

# endpoint configuration
endpoints:
  shutdown:
    enabled: true

# database configuration
spring:
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false

  datasource:
    url: jdbc:mysql:thin://localhost:3306/messagegateway
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:ethieTieCh8ahv}
    driver-class-name: org.drizzle.jdbc.DrizzleDriver

# Status Callback configuration for Twilio. Port will be taken from server configuration
hostconfig:
  host: localhost
  protocol: http

callbackconfig:
  host: 0.0.0.0
  protocol: http
  port: 5000

application:
  version: 1.0.0

management:
  endpoint:
    health:
      probes:
        enabled: true
      liveness:
        enabled: true
      readiness:
        enabled: true

providerSource:
  fromdatabase: disabled
  fromyml: enabled

providerKeys:
  telerivetApiKey: eKiC1_JWdKy7eaTGQFHxXXjXjacr60W9Zntl
  telerivetProjectId: PJ5ff552ce01d2978c

provider:
  telerivet:
    enabled: true
    id: 2
  rapidpro:
    enabled: false
    id: 3

operationsconfig:
  tenantid: "Fineract-Platform-TenantId"
  tenantidvalue : "default"
  tenantappkey: "Fineract-Tenant-App-Key"
  tenantappvalue: "123456543234abdkdkdkd"

messagegatewayconfig:
  host: 127.0.0.1
  protocol: http
  port: 9191

logging:
  level:
    org:
      apache:
        camel=DEBUG:
    root: INFO

kafka:
  brokers: "kafka:9092"

importer:
  kafka:
    topic: "zeebe-export"

camel:
  server-port: 5009
  springboot:
    main-run-controller: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true
zeebe:
  client:
    max-execution-threads: 100
    number-of-workers: 5
    evenly-allocated-max-jobs: "#{${zeebe.client.max-execution-threads} / ${zeebe.client.number-of-workers}}"
    ttl: 30000
    security:
      plaintext: true
    broker:
      gateway-address: "127.0.0.1:26500"
  broker:
    contactpoint: "localhost:26500"
  worker:
    timer: "PT5S"